//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public Compra()
        {
            this.Pedidoes = new HashSet<Pedido>();
        }
    
        public int Id { get; set; }
        public long compradoQuantity { get; set; }
        public int ProductoId { get; set; }
    
        public virtual ICollection<Pedido> Pedidoes { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
